"""empty message

Revision ID: 569cda36c909
Revises: 9a9d9c7d2252
Create Date: 2023-08-31 05:27:18.321159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569cda36c909'
down_revision = '9a9d9c7d2252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_history')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATE(), nullable=True))

    op.create_table('watch_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('watched_at', sa.DATE(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('video_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_watch_history_user_id_users'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='fk_watch_history_video_id_videos'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
