"""autogen

Revision ID: 8576f6551c03
Revises: c654d2aab569
Create Date: 2023-09-07 03:43:16.443013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8576f6551c03'
down_revision = 'c654d2aab569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('following')
    op.drop_table('categories')
    op.drop_table('likes')
    op.drop_table('video_categories')
    op.drop_table('channels')
    op.drop_table('users')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_videos_channel_id_channels', type_='foreignkey')
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_videos_channel_id_channels', 'channels', ['channel_id'], ['id'])

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('_password_hash', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('channels',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('video_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_video_categories_category_id_categories'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='fk_video_categories_video_id_videos'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('video_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_likes_user_id_users'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='fk_likes_video_id_videos'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('following',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('channel_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name='fk_following_channel_id_channels'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_following_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('video_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_comments_user_id_users'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], name='fk_comments_video_id_videos'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
