"""auto

Revision ID: aa3e7d90e2a5
Revises: fefd228bea0d
Create Date: 2023-09-06 21:47:04.200547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3e7d90e2a5'
down_revision = 'fefd228bea0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_videos_channel_id_channels'), 'channels', ['channel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_videos_channel_id_channels'), type_='foreignkey')
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###
