"""auto

Revision ID: fefd228bea0d
Revises: 676e809da3bd
Create Date: 2023-09-06 21:46:10.057511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefd228bea0d'
down_revision = '676e809da3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_videos_channel_id_channels', type_='foreignkey')
        batch_op.drop_column('channel_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_videos_channel_id_channels', 'channels', ['channel_id'], ['id'])

    # ### end Alembic commands ###
